buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.4.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'android-library'

android {
    compileSdk 36

    defaultConfig {
        minSdkVersion 35
        targetSdkVersion 35
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFile getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }

    lintOptions {
    	abortOnError false
	}

	namespace 'com.imagine'
}

dependencies {
    implementation "com.android.support:support-v4:28.0.0"
}

